name: Node.js Package Release

on:
  release:
    types: [created]

jobs:
  build-publish-pkg:
    name: Build and push package on node 18
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Yarn Build
        run: yarn build

      - name: Publish package to npmjs
        run: npm publish
